### ISSUE TITLE
我的cgdb无法通过在CGDB模式下键入I T两个命令打开tty窗口进行i/o输入

### ISSUE THREAD

**Issue by awarewen** [leeyiw/cgdb-manual-in-chinese#22]

**Comment by youhuangla** [comment]
可能是版本的问题，作者在[Ctrl \- T doesn't seem to work \(cgdb 0\.7\.0\) · Issue \#193 · cgdb/cgdb](https://github.com/cgdb/cgdb/issues/193)写了那个new branch可以用，但是最新的版本貌似不行
